quiet: true
download-external-modules: true

framework:
  - kubernetes

skip-check:
  # Example: if warnings about missing resources in Ingress are not needed
  - CKV_K8S_21  # Ingress should specify host

evaluate-variables: true

# Paths to scan
directory:
  - apps
  - policy
