title = "Gitleaks config"

[allowlist]
description = "Allow common false positives"
regexes = [
  '''(?i)AKIA[0-9A-Z]{16}''', # AWS
]
files = [
  '''.gitignore''',
  '''.yamllint.yml''',
  '''.gitleaks.toml''',
]

[rules]
# Block secrets from being committed directly in Application/values
[[rules]]
description = "Generic secret"
regex = '''(?i)(password|secret|token|api[_-]?key)\s*[:=]\s*['"][A-Za-z0-9\-\._]+['"]'''
