repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args: ["--config=.gitleaks.toml"]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.276
    hooks:
      - id: checkov
        args: ["--framework", "kubernetes"]
        files: \.(yaml|yml)$
